{% set name = "xevo" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
 git_url: https://giorgosR:0314kemo@github.com/giorgosR/xevo
# path: ../archive-latest.tar.gz
 
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    # - libblas
    # - libcblas
    # - liblapack
    - xtensor >=0.21.2,<0.22.0
  run:
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xevo  # [unix]
    - test -f ${PREFIX}/include/xevo/ga.hpp  # [unix]
    - test -f ${PREFIX}/include/xevo/analytical_functions.hpp  # [unix]
    - test -f ${PREFIX}/include/xevo/functors.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xevo/xevoConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xevo/xevoConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xevo\ga.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xevo\analytical_functions.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xevo\functors.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xevoConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xevoConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/giorgosR/xevo
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The XEVO
  description: C++ recipes for nature inspyred optimisation algorithms
#  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/giorgosR/xevo

extra:
  recipe-maintainers:
    - giorgosR