{% set name = "xnio" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
 git_url: https://giorgosR:0314kemo@github.com/giorgosR/xnio
# path: ../archive-latest.tar.gz
 
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    # - libblas
    # - libcblas
    # - liblapack
    - xtensor >=0.21.2,<0.22.0
  run:
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xnio  # [unix]
    - test -f ${PREFIX}/include/xnio/ga.hpp  # [unix]
    - test -f ${PREFIX}/include/xnio/analytical_functions.hpp  # [unix]
    - test -f ${PREFIX}/include/xnio/functors.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xnio/xnioConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xnio/xnioConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xnio\ga.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xnio\analytical_functions.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\xnio\functors.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xnioConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xnioConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/giorgosR/xnio
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The XNIO
  description: C++ recipes for nature inspyred optimisation algorithms
#  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/giorgosR/xnio

extra:
  recipe-maintainers:
    - giorgosR